# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='update',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
